# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 16:54
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171004_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='getting_there',
        ),
        migrations.RemoveField(
            model_name='region',
            name='polygon',
        ),
        migrations.AddField(
            model_name='region',
            name='multipolygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, default=None, geography=True, null=True, srid=4326),
        ),
    ]
