# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 18:37
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('getting_there', models.TextField(verbose_name='How to get there')),
                ('area', django.contrib.gis.db.models.fields.MultiPolygonField(default=None, geography=True, null=True, srid=4326, verbose_name='Area')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('getting_there', models.TextField(verbose_name='How to get there')),
                ('contents', django.contrib.gis.db.models.fields.PolygonField(default=None, geography=True, null=True, srid=4326, verbose_name='Area')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('getting_there', models.TextField(verbose_name='How to get there')),
                ('first_ascent_names', models.CharField(max_length=50, verbose_name='First Ascender')),
                ('first_ascent_date', models.DateField(verbose_name='First Ascent Date')),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, default=None, geography=True, null=True, srid=4326, verbose_name='Coordinates')),
                ('yds_class', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='YDS class')),
                ('yds_decimal', models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='YDS 5th class decimal')),
                ('yds_letter', models.CharField(blank=True, choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], default=None, max_length=1, null=True, verbose_name='YDS difficulty letter')),
                ('yds_modifier', models.CharField(blank=True, choices=[('+', 'plus'), ('-', 'minus')], default=None, max_length=1, null=True, verbose_name='YDS difficulty modifier')),
                ('yds_protection', models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG13', 'PG13'), ('R', 'R'), ('X', 'X')], default='G', max_length=4, verbose_name='YDS protection rating')),
                ('yds_length', models.CharField(choices=[('I', 'I: 1-2 hours'), ('II', 'II: Less than a half-day'), ('III', 'III: Half day'), ('IV', 'IV: Full day'), ('V', 'V: 2-3 days'), ('VI', 'VI: 4-6 days'), ('VII', 'VII: 1 week or longer')], default='I', max_length=3, verbose_name='YDS length grade')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Area')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='region',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Region'),
        ),
    ]
