# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 21:35
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='area',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(default=None, null=True, srid=4326, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='route',
            name='first_ascent_date',
            field=models.DateField(verbose_name='First Ascent Date'),
        ),
    ]
