# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 22:38
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170918_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('getting_there', models.TextField(verbose_name='How to get there')),
                ('contents', django.contrib.gis.db.models.fields.PolygonField(default=None, geography=True, null=True, srid=4326, verbose_name='Area')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='region',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Region'),
        ),
    ]
