# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 18:47
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170921_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='area',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, default=None, geography=True, null=True, srid=4326, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='region',
            name='contents',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, default=None, geography=True, null=True, srid=4326, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='route',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=None, geography=True, null=True, srid=4326, verbose_name='Coordinates'),
        ),
        migrations.AlterField(
            model_name='route',
            name='yds_decimal',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='YDS 5th class decimal'),
        ),
        migrations.AlterField(
            model_name='route',
            name='yds_letter',
            field=models.CharField(blank=True, choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], default=None, max_length=1, null=True, verbose_name='YDS difficulty letter'),
        ),
        migrations.AlterField(
            model_name='route',
            name='yds_modifier',
            field=models.CharField(blank=True, choices=[('+', 'plus'), ('-', 'minus')], default=None, max_length=1, null=True, verbose_name='YDS difficulty modifier'),
        ),
    ]
